general:
  kafka-topic: trader-updates
  incentive-api-url: "http://localhost:8080/incentive"

spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.jpmc.midascore.foundation.Transaction
        spring.json.trusted.packages: com.jpmc.midascore.foundation